### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'method' and 'int'

### ISSUE THREAD

**Issue by rm1984** [tenable/integration-cef#3]
Hello,
when I run tenable-cef v1.0.0 I get the following error several times:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tenable_cef/pool.py", line 18, in run
    func(*args, **kargs)
  File "/usr/local/lib/python3.9/dist-packages/tenable_cef/transform.py", line 44, in _transform_vulnerability
    rt=arrow.get(vuln.get('last_found')).timestamp * 1000,
TypeError: unsupported operand type(s) for *: 'method' and 'int'
```

My API keys are correct and my Tenable.io user is an administrator.
Thanks.

**Comment by SteveMcGrath** [comment]
Thats an issue with arrow and how they updated their timestamp interface.
